const resObj=[
    {
      data:{
          "id": "266027",
          "name": "KFC",
          "cloudinaryImageId": "ee5f8e06b300efc07c9fe3f4df40dfc4",
          "locality": "Manyata Embassy Business Park",
          "areaName": "Nagawara",
          "costForTwo": "₹400 for two",
          "cuisines": [
            "Burgers",
            "Beverages",
            "Cafe",
            "Desserts"
          ],
          "avgRating": 4.1,
      },
      data:{
          "id": "266028",
          "name": "MCD",
          "cloudinaryImageId": "ee5f8e06b300efc07c9fe3f4df40dfc4",
          "locality": "Manyata Embassy Business Park",
          "areaName": "Nagawara",
          "costForTwo": "₹400 for two",
          "cuisines": [
            "Burgers",
            "Beverages",
            "Cafe",
            "Desserts"
          ],
          "avgRating": 4.4,
      },
      data:{
          "id": "266038",
          "name": "Coffe day",
          "cloudinaryImageId": "ee5f8e06b300efc07c9fe3f4df40dfc4",
          "locality": "Manyata Embassy Business Park",
          "areaName": "Nagawara",
          "costForTwo": "₹400 for two",
          "cuisines": [
            "Burgers",
            "Beverages",
            "Cafe",
            "Desserts"
          ],
          "avgRating": 4.4,
      },
      data:{
          "id": "266048",
          "name": "Bangarpet pani puri",
          "cloudinaryImageId": "ee5f8e06b300efc07c9fe3f4df40dfc4",
          "locality": "Manyata Embassy Business Park",
          "areaName": "Nagawara",
          "costForTwo": "₹400 for two",
          "cuisines": [
            "Burgers",
            "Beverages",
            "Cafe",
            "Desserts"
          ],
          "avgRating": 4.4,
      },
      data:{
          "id": "266028",
          "name": "MCD",
          "cloudinaryImageId": "ee5f8e06b300efc07c9fe3f4df40dfc4",
          "locality": "Manyata Embassy Business Park",
          "areaName": "Nagawara",
          "costForTwo": "₹400 for two",
          "cuisines": [
            "Burgers",
            "Beverages",
            "Cafe",
            "Desserts"
          ],
          "avgRating": 4.4,
      },
      data:{
          "id": "266018",
          "name": "Biryani zone",
          "cloudinaryImageId": "ee5f8e06b300efc07c9fe3f4df40dfc4",
          "locality": "Manyata Embassy Business Park",
          "areaName": "Nagawara",
          "costForTwo": "₹400 for two",
          "cuisines": [
            "Burgers",
            "Beverages",
            "Cafe",
            "Desserts"
          ],
          "avgRating": 3.8,
      },
      
    }]
    
          export default resObj;
    
    // const restList = [
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "15962",
    //       name: "A2B - Adyar Ananda Bhavan",
    //       uuid: "5043455d-712a-48c0-bcec-18a63b7434ce",
    //       city: "1",
    //       area: "Frazer Town",
    //       totalRatingsString: "10000+ ratings",
    //       cloudinaryImageId: "pbfpu4f1h5qo1hexac0g",
    //       cuisines: ["South Indian", "North Indian", "Sweets", "Chinese"],
    //       tags: [],
    //       costForTwo: 30000,
    //       costForTwoString: "₹300 FOR TWO",
    //       deliveryTime: 39,
    //       minDeliveryTime: 39,
    //       maxDeliveryTime: 39,
    //       slaString: "39 MINS",
    //       lastMileTravel: 4.5,
    //       slugs: {
    //         restaurant: "a2b-adyar-ananda-bhavan-ulsoor-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "37/3, Tank Road, Civil Station, Near Ulsoor Lake, Opp. to Shanthi Sagar, Bangalore 42",
    //       locality: "Pulikeshi Nagar",
    //       parentId: 22,
    //       unserviceable: false,
    //       veg: true,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       ribbon: [
    //         {
    //           type: "PROMOTED",
    //         },
    //       ],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 4000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 4000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "4000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID:
    //         "cid=7218667~p=1~eid=00000189-02a9-515b-1b07-a0aa00c80109~srvts=1687966798171",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "4.5 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "₹150 OFF",
    //         subHeader: "ABOVE ₹299",
    //         discountTag: "FLAT DEAL",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "15962",
    //         deliveryTime: 39,
    //         minDeliveryTime: 39,
    //         maxDeliveryTime: 39,
    //         lastMileTravel: 4.5,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: true,
    //       avgRating: "4.4",
    //       totalRatings: 10000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "3241",
    //       name: "Meghana Foods",
    //       uuid: "93695df0-56e1-417e-b9a8-32084ebaadaf",
    //       city: "1",
    //       area: "Ashok Nagar",
    //       totalRatingsString: "10000+ ratings",
    //       cloudinaryImageId: "e0vvulfbahjxjz6k4uwi",
    //       cuisines: [
    //         "Biryani",
    //         "Andhra",
    //         "South Indian",
    //         "North Indian",
    //         "Chinese",
    //         "Seafood",
    //       ],
    //       tags: [],
    //       costForTwo: 50000,
    //       costForTwoString: "₹500 FOR TWO",
    //       deliveryTime: 26,
    //       minDeliveryTime: 26,
    //       maxDeliveryTime: 26,
    //       slaString: "26 MINS",
    //       lastMileTravel: 2.4000000953674316,
    //       slugs: {
    //         restaurant: "meghana-foods-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "57/1, 1st Floor, Jayalaxmi Chambers, Next to Old Galaxy Theatre,Residency Road, Bangalore",
    //       locality: "Residency Road",
    //       parentId: 635,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "2.4 kms",
    //       hasSurge: false,
    //       sla: {
    //         restaurantId: "3241",
    //         deliveryTime: 26,
    //         minDeliveryTime: 26,
    //         maxDeliveryTime: 26,
    //         lastMileTravel: 2.4000000953674316,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "4.5",
    //       totalRatings: 10000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "210945",
    //       name: "Royal Restaurant",
    //       uuid: "9b33bca4-65e6-4a26-af3e-f47c4476ed4d",
    //       city: "1",
    //       area: "Shivajinagar",
    //       totalRatingsString: "5000+ ratings",
    //       cloudinaryImageId: "yicweopn4lzcjlqy4jvq",
    //       cuisines: ["Chinese", "North Indian", "Tandoor"],
    //       tags: [],
    //       costForTwo: 30000,
    //       costForTwoString: "₹300 FOR TWO",
    //       deliveryTime: 39,
    //       minDeliveryTime: 39,
    //       maxDeliveryTime: 39,
    //       slaString: "39 MINS",
    //       lastMileTravel: 3,
    //       slugs: {
    //         restaurant: "royal-restaurant-central-bangalore-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "Broadway Road Police Station, HKP Road, Sulthangunta, Shivajinagar, Bengaluru, Bangalore Urban, Karnataka, India",
    //       locality: "Sulthangunta",
    //       parentId: 2896,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 4000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 4000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "4000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "3 kms",
    //       hasSurge: false,
    //       sla: {
    //         restaurantId: "210945",
    //         deliveryTime: 39,
    //         minDeliveryTime: 39,
    //         maxDeliveryTime: 39,
    //         lastMileTravel: 3,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "3.9",
    //       totalRatings: 5000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "342643",
    //       name: "The Pizza Bakery",
    //       uuid: "fdf44d9a-3d5f-4c7d-aac7-80bc3a1d68d0",
    //       city: "1",
    //       area: "Ashok Nagar",
    //       totalRatingsString: "1000+ ratings",
    //       cloudinaryImageId: "l7zme8yryk6adeakj6jy",
    //       cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Continental"],
    //       tags: [],
    //       costForTwo: 70000,
    //       costForTwoString: "₹700 FOR TWO",
    //       deliveryTime: 36,
    //       minDeliveryTime: 36,
    //       maxDeliveryTime: 36,
    //       slaString: "36 MINS",
    //       lastMileTravel: 1.2999999523162842,
    //       slugs: {
    //         restaurant: "the-pizza-bakery-central-bangalore-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "The Pizza Bakery, 86, Spenser Building, Church Street, Bangalore 560001",
    //       locality: "Church Street",
    //       parentId: 11108,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       ribbon: [
    //         {
    //           type: "PROMOTED",
    //         },
    //       ],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID:
    //         "cid=7177267~p=4~eid=00000189-02a9-515b-1b07-a0ab00c80404~srvts=1687966798171",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "1.2 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "30% OFF",
    //         subHeader: "UPTO ₹75",
    //         discountTag: "",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "342643",
    //         deliveryTime: 36,
    //         minDeliveryTime: 36,
    //         maxDeliveryTime: 36,
    //         lastMileTravel: 1.2999999523162842,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: true,
    //       avgRating: "4.4",
    //       totalRatings: 1000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "30531",
    //       name: "Hotel Empire",
    //       uuid: "fdf6686f-6f39-4a90-8eb0-6dc7abf82643",
    //       city: "1",
    //       area: "Brigade Road",
    //       totalRatingsString: "10000+ ratings",
    //       cloudinaryImageId: "qltgnkyywuo5gmnpqzbm",
    //       cuisines: ["North Indian", "Kebabs", "Biryani"],
    //       tags: [],
    //       costForTwo: 45000,
    //       costForTwoString: "₹450 FOR TWO",
    //       deliveryTime: 32,
    //       minDeliveryTime: 32,
    //       maxDeliveryTime: 32,
    //       slaString: "32 MINS",
    //       lastMileTravel: 2.0999999046325684,
    //       slugs: {
    //         restaurant: "empire-restaurant-central-bangalore-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "Empire SuitesNo.35, Castle Street, Off Brigade Road,Bengaluru, Karnataka 560025",
    //       locality: "Brigade Road",
    //       parentId: 475,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "2 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "10% OFF",
    //         subHeader: "ABOVE ₹500",
    //         discountTag: "FLAT DEAL",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "30531",
    //         deliveryTime: 32,
    //         minDeliveryTime: 32,
    //         maxDeliveryTime: 32,
    //         lastMileTravel: 2.0999999046325684,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "4.3",
    //       totalRatings: 10000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "684427",
    //       name: "Cafe Amudham",
    //       uuid: "e56f2694-6e06-4135-9c08-eb87c2496398",
    //       city: "1",
    //       area: "Jayanagar",
    //       totalRatingsString: "1000+ ratings",
    //       cloudinaryImageId: "0bcdca61f3cd1e9135b98328593d044f",
    //       cuisines: ["South Indian", "Snacks"],
    //       tags: [],
    //       costForTwo: 40000,
    //       costForTwoString: "₹400 FOR TWO",
    //       deliveryTime: 31,
    //       minDeliveryTime: 31,
    //       maxDeliveryTime: 31,
    //       slaString: "31 MINS",
    //       lastMileTravel: 4,
    //       slugs: {
    //         restaurant: "cafe-amudham-jayanagar-jayanagar",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "No. 192, , Lalbhagh  Siddapura, Jayanagar 1st Block, Ward No. 144,  Bangalore, B.B.M.P South, Karnataka-560011",
    //       locality: "Lalbhagh  Siddapura",
    //       parentId: 396620,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       ribbon: [
    //         {
    //           type: "PROMOTED",
    //         },
    //       ],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 4000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 4000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "4000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID:
    //         "cid=7159548~p=7~eid=00000189-02a9-515b-1b07-a0ac00c80723~srvts=1687966798171",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "4 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "20% OFF",
    //         subHeader: "UPTO ₹50",
    //         discountTag: "",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "684427",
    //         deliveryTime: 31,
    //         minDeliveryTime: 31,
    //         maxDeliveryTime: 31,
    //         lastMileTravel: 4,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: true,
    //       avgRating: "4.5",
    //       totalRatings: 1000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "245536",
    //       name: "Brik Oven",
    //       uuid: "c741d511-f4db-4474-a763-b63442f0d579",
    //       city: "1",
    //       area: "Race Course Road",
    //       totalRatingsString: "1000+ ratings",
    //       cloudinaryImageId: "49352a71022a5b08a8361306ba253892",
    //       cuisines: ["Italian", "Pizzas", "Desserts", "Beverages"],
    //       tags: [],
    //       costForTwo: 70000,
    //       costForTwoString: "₹700 FOR TWO",
    //       deliveryTime: 36,
    //       minDeliveryTime: 36,
    //       maxDeliveryTime: 36,
    //       slaString: "36 MINS",
    //       lastMileTravel: 3,
    //       slugs: {
    //         restaurant: "brik-oven-rajajinagar-rajajinagar",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "The Courtyard, Prestiage Trade Towers,Unitle-6 ,No.45/1, palace Road,High Grounds,Sampangi Ramanagar,Bengaluru",
    //       locality: "Race Course Road",
    //       parentId: 7389,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       ribbon: [
    //         {
    //           type: "PROMOTED",
    //         },
    //       ],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 4000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 4000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "4000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID:
    //         "cid=6918781~p=10~eid=00000189-02a9-515b-1b07-a0ad00c80a62~srvts=1687966798171",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "3 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "15% OFF",
    //         subHeader: "ABOVE ₹1300",
    //         discountTag: "FLAT DEAL",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "245536",
    //         deliveryTime: 36,
    //         minDeliveryTime: 36,
    //         maxDeliveryTime: 36,
    //         lastMileTravel: 3,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: true,
    //       avgRating: "4.2",
    //       totalRatings: 1000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "196047",
    //       name: "New Taj Darbar",
    //       uuid: "94a6fc19-e819-4450-b52f-a96c5a32d565",
    //       city: "1",
    //       area: "Shivajinagar",
    //       totalRatingsString: "10000+ ratings",
    //       cloudinaryImageId: "nfieyqgxk1omknxfbluj",
    //       cuisines: ["Biryani", "Indian", "Chinese", "Tandoor", "Seafood"],
    //       tags: [],
    //       costForTwo: 30000,
    //       costForTwoString: "₹300 FOR TWO",
    //       deliveryTime: 44,
    //       minDeliveryTime: 44,
    //       maxDeliveryTime: 44,
    //       slaString: "44 MINS",
    //       lastMileTravel: 2.5999999046325684,
    //       slugs: {
    //         restaurant: "new-taj-darbar-central-bangalore-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address: "New Taj Darbar, Shivaji Nagar, Bengaluru, Karnataka, India",
    //       locality: "Saint Mary's Church Road",
    //       parentId: 148190,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "2.5 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "₹100 OFF",
    //         subHeader: "ABOVE ₹499",
    //         discountTag: "FLAT DEAL",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "196047",
    //         deliveryTime: 44,
    //         minDeliveryTime: 44,
    //         maxDeliveryTime: 44,
    //         lastMileTravel: 2.5999999046325684,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "3.4",
    //       totalRatings: 10000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "252618",
    //       name: "Al-Bek",
    //       uuid: "9cd12cc5-caf6-4db1-99f2-38644395aa67",
    //       city: "1",
    //       area: "Rajajinagar",
    //       totalRatingsString: "5000+ ratings",
    //       cloudinaryImageId: "teg1rujhfwroaoig95qs",
    //       cuisines: ["Arabian", "Tandoor", "Biryani"],
    //       tags: [],
    //       costForTwo: 50000,
    //       costForTwoString: "₹500 FOR TWO",
    //       deliveryTime: 33,
    //       minDeliveryTime: 33,
    //       maxDeliveryTime: 33,
    //       slaString: "33 MINS",
    //       lastMileTravel: 6.400000095367432,
    //       slugs: {
    //         restaurant: "al-bek-rajajinagar-rajajinagar",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "349/74, 12th Main, 6th BLOCK Opp Mayura Hotel, Bangalore- 560010",
    //       locality: "6th Block",
    //       parentId: 9911,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 6300,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 6300,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "6300",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 1,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "6.4 kms",
    //       hasSurge: false,
    //       sla: {
    //         restaurantId: "252618",
    //         deliveryTime: 33,
    //         minDeliveryTime: 33,
    //         maxDeliveryTime: 33,
    //         lastMileTravel: 6.400000095367432,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "IT_IS_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "4.0",
    //       totalRatings: 5000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "484939",
    //       name: "Salt - Indian Restaurant Bar & Grill",
    //       uuid: "3e3c11a4-ba2b-447a-af99-a89ce951ad26",
    //       city: "1",
    //       area: "Whitefield",
    //       totalRatingsString: "100+ ratings",
    //       cloudinaryImageId: "bsvhzfo27ivluydh5lwh",
    //       cuisines: ["South Indian", "Indian", "Combo", "Biryani", "Desserts"],
    //       tags: [],
    //       costForTwo: 100000,
    //       costForTwoString: "₹1000 FOR TWO",
    //       deliveryTime: 36,
    //       minDeliveryTime: 36,
    //       maxDeliveryTime: 36,
    //       slaString: "36 MINS",
    //       lastMileTravel: 0.20000000298023224,
    //       slugs: {
    //         restaurant:
    //           "salt---indian-restaurant-bar-&-grill-central-bangalore-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "No 24, Vittal Malya Road, Concord and Canberra Block 2nd Level, UB City Bangalore, B.B.M.P East, Karnataka-560001",
    //       locality: "Whitefield",
    //       parentId: 22457,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       ribbon: [
    //         {
    //           type: "PROMOTED",
    //         },
    //       ],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID:
    //         "cid=7177453~p=13~eid=00000189-02a9-515b-1b07-a0ae00c80d43~srvts=1687966798171",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "0.2 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "50% OFF",
    //         subHeader: "UPTO ₹100",
    //         discountTag: "",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "484939",
    //         deliveryTime: 36,
    //         minDeliveryTime: 36,
    //         maxDeliveryTime: 36,
    //         lastMileTravel: 0.20000000298023224,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: true,
    //       avgRating: "4.3",
    //       totalRatings: 100,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "4046",
    //       name: "Sri Udupi Park",
    //       uuid: "5b811b78-56d2-4d80-9681-7630cb3904c6",
    //       city: "1",
    //       area: "Residency Road",
    //       totalRatingsString: "10000+ ratings",
    //       cloudinaryImageId: "tfbnpd65irvhp9iwhbtk",
    //       cuisines: [
    //         "North Indian",
    //         "South Indian",
    //         "Chinese",
    //         "Chaat",
    //         "Beverages",
    //       ],
    //       tags: [],
    //       costForTwo: 20000,
    //       costForTwoString: "₹200 FOR TWO",
    //       deliveryTime: 38,
    //       minDeliveryTime: 38,
    //       maxDeliveryTime: 38,
    //       slaString: "38 MINS",
    //       lastMileTravel: 2.299999952316284,
    //       slugs: {
    //         restaurant: "veg-feast-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address: "57, Opposite Galaxy Mall, Residency Road, Bangalore",
    //       locality: "Galaxy Mall",
    //       parentId: 4284,
    //       unserviceable: false,
    //       veg: true,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "2.2 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "10% OFF",
    //         subHeader: "ABOVE ₹700",
    //         discountTag: "FLAT DEAL",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "4046",
    //         deliveryTime: 38,
    //         minDeliveryTime: 38,
    //         maxDeliveryTime: 38,
    //         lastMileTravel: 2.299999952316284,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "4.4",
    //       totalRatings: 10000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "34269",
    //       name: "Hamza hotel",
    //       uuid: "849f25cd-8e16-4049-b164-de833e49cfcc",
    //       city: "1",
    //       area: "Shivajinagar",
    //       totalRatingsString: "10000+ ratings",
    //       cloudinaryImageId: "rea8vn4ubttcd6gcue3p",
    //       cuisines: ["Continental", "Street Food"],
    //       tags: [],
    //       costForTwo: 30000,
    //       costForTwoString: "₹300 FOR TWO",
    //       deliveryTime: 37,
    //       minDeliveryTime: 37,
    //       maxDeliveryTime: 37,
    //       slaString: "37 MINS",
    //       lastMileTravel: 2.9000000953674316,
    //       slugs: {
    //         restaurant: "hamza-hotel-shivajinagar-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address: "#19HKP road (broadway)Shivajinagar Bangalore 560051",
    //       locality: "HKP road",
    //       parentId: 21662,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "2.9 kms",
    //       hasSurge: false,
    //       sla: {
    //         restaurantId: "34269",
    //         deliveryTime: 37,
    //         minDeliveryTime: 37,
    //         maxDeliveryTime: 37,
    //         lastMileTravel: 2.9000000953674316,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "4.2",
    //       totalRatings: 10000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "241420",
    //       name: "Misu",
    //       uuid: "807f2167-b89b-4df9-a139-a45655a36d5e",
    //       city: "1",
    //       area: "Seshadripuram",
    //       totalRatingsString: "1000+ ratings",
    //       cloudinaryImageId: "sfiv4ftxpr8lihrj9scz",
    //       cuisines: [
    //         "Asian",
    //         "Chinese",
    //         "Vietnamese",
    //         "Malaysian",
    //         "Sushi",
    //         "Singaporean",
    //         "Desserts",
    //       ],
    //       tags: [],
    //       costForTwo: 130000,
    //       costForTwoString: "₹1300 FOR TWO",
    //       deliveryTime: 39,
    //       minDeliveryTime: 39,
    //       maxDeliveryTime: 39,
    //       slaString: "39 MINS",
    //       lastMileTravel: 3,
    //       slugs: {
    //         restaurant: "misu-majestic-majestic",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "MISU TRADE TOWERS, PRESTIGE TRADE TOWERS, GROUND FLOOR PLACE ROAD",
    //       locality: "Palace Road",
    //       parentId: 7415,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       ribbon: [
    //         {
    //           type: "PROMOTED",
    //         },
    //       ],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 4000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 4000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "4000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID:
    //         "cid=6918696~p=16~eid=00000189-02a9-515b-1b07-a0af00c8104b~srvts=1687966798171",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "3 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "10% OFF",
    //         subHeader: "ABOVE ₹1000",
    //         discountTag: "FLAT DEAL",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "241420",
    //         deliveryTime: 39,
    //         minDeliveryTime: 39,
    //         maxDeliveryTime: 39,
    //         lastMileTravel: 3,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: true,
    //       avgRating: "4.2",
    //       totalRatings: 1000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "5938",
    //       name: "Burger King",
    //       uuid: "15bfac38-f648-4d1f-8a91-7bbd6f9a4c1e",
    //       city: "1",
    //       area: "Shivaji Nagar",
    //       totalRatingsString: "10000+ ratings",
    //       cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    //       cuisines: ["Burgers", "American"],
    //       tags: [],
    //       costForTwo: 35000,
    //       costForTwoString: "₹350 FOR TWO",
    //       deliveryTime: 38,
    //       minDeliveryTime: 38,
    //       maxDeliveryTime: 38,
    //       slaString: "38 MINS",
    //       lastMileTravel: 2.700000047683716,
    //       slugs: {
    //         restaurant: "burger-king-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "Unit no 111/4, and 8/2, Asha Gallary, Opposite to west side , Commercial Street, Bangalore-  5600001",
    //       locality: "Tasker Town",
    //       parentId: 166,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "2.7 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "EVERY ITEM",
    //         subHeader: "@ ₹129",
    //         discountTag: "",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "5938",
    //         deliveryTime: 38,
    //         minDeliveryTime: 38,
    //         maxDeliveryTime: 38,
    //         lastMileTravel: 2.700000047683716,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "4.1",
    //       totalRatings: 10000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    //   {
    //     type: "restaurant",
    //     data: {
    //       type: "F",
    //       id: "10575",
    //       name: "Pizza Hut",
    //       uuid: "92a5861b-2786-4cac-92c2-341cdffd1b27",
    //       city: "1",
    //       area: "Shanti Nagar",
    //       totalRatingsString: "5000+ ratings",
    //       cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    //       cuisines: ["Pizzas"],
    //       tags: [],
    //       costForTwo: 60000,
    //       costForTwoString: "₹600 FOR TWO",
    //       deliveryTime: 31,
    //       minDeliveryTime: 31,
    //       maxDeliveryTime: 31,
    //       slaString: "31 MINS",
    //       lastMileTravel: 2.0999999046325684,
    //       slugs: {
    //         restaurant: "pizza-hut-oshngness-road-central-bangalore",
    //         city: "bangalore",
    //       },
    //       cityState: "1",
    //       address:
    //         "4/1, O'Shaughnessy Road, Richmond Town, Langford Gardens, Bengaluru, Karnataka 560025",
    //       locality: "Shanti Nagar",
    //       parentId: 721,
    //       unserviceable: false,
    //       veg: false,
    //       select: false,
    //       favorite: false,
    //       tradeCampaignHeaders: [],
    //       chain: [],
    //       feeDetails: {
    //         fees: [
    //           {
    //             name: "distance",
    //             fee: 3000,
    //             message: "",
    //           },
    //           {
    //             name: "time",
    //             fee: 0,
    //             message: "",
    //           },
    //           {
    //             name: "special",
    //             fee: 0,
    //             message: "",
    //           },
    //         ],
    //         totalFees: 3000,
    //         message: "",
    //         title: "Delivery Charge",
    //         amount: "3000",
    //         icon: "",
    //       },
    //       availability: {
    //         opened: true,
    //         nextOpenMessage: "",
    //         nextCloseMessage: "",
    //       },
    //       longDistanceEnabled: 0,
    //       rainMode: "NONE",
    //       thirdPartyAddress: false,
    //       thirdPartyVendor: "",
    //       adTrackingID: "",
    //       badges: {
    //         imageBased: [],
    //         textBased: [],
    //         textExtendedBadges: [],
    //       },
    //       lastMileTravelString: "2 kms",
    //       hasSurge: false,
    //       aggregatedDiscountInfoV3: {
    //         header: "50% OFF",
    //         subHeader: "UPTO ₹100",
    //         discountTag: "",
    //         headerTypeV2: 0,
    //       },
    //       sla: {
    //         restaurantId: "10575",
    //         deliveryTime: 31,
    //         minDeliveryTime: 31,
    //         maxDeliveryTime: 31,
    //         lastMileTravel: 2.0999999046325684,
    //         lastMileDistance: 0,
    //         serviceability: "SERVICEABLE",
    //         rainMode: "NONE",
    //         longDistance: "NOT_LONG_DISTANCE",
    //         preferentialService: false,
    //         iconType: "EMPTY",
    //       },
    //       promoted: false,
    //       avgRating: "3.9",
    //       totalRatings: 5000,
    //       new: false,
    //     },
    //     subtype: "basic",
    //   },
    // ];
    
    // export default restList;